apiVersion: v1
kind: ConfigMap
metadata:
  namespace: itsmetommy
  labels:
    name: redis
  name: redis-cluster-conf
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
